name: Enable/Disable Maintenance Mode
run-name: Enable/Disable Maintenance Mode for ${{ inputs.environment }}

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      container-name:
        type: string
        required: true
      enable:
        type: boolean
        required: true
    secrets:
      SSH_HOST:
        required: true
      SSH_PORT:
        required: true
      SSH_USERNAME:
        required: true
      SSH_KEY:
        required: true

jobs:
  enable-maintenance:
    if: ${{ inputs.enable }}
    name: Enable maintenance mode
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Enable maintenance mode'
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          timeout: "30s"
          script: |
            cd ${{ vars.DEPLOYMENT_COMPOSE_TARGET }}/
            # Check if container is running before running maintenance command
            if docker compose ps --status=running ${{ inputs.container-name }} | grep -q '${{ inputs.container-name }}'; then
              docker compose exec ${{ inputs.container-name }} sh -c 'maintenance 1'
              if [ $? != 0 ]
              then
                echo "WARN: Could not enable maintenance mode!"
                echo "WARN: Proceeding with deployment..."
              fi
            else
              echo "${{ inputs.container-name }} container is not running, skipping maintenance command"
            fi

  disable-maintenance:
    if: ${{ !inputs.enable }}
    name: Disable maintenance mode
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Disable maintenance mode'
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          timeout: "30s"
          script: |
            cd ${{ vars.DEPLOYMENT_COMPOSE_TARGET }}/
            # Check if container is running before running maintenance command
            if docker compose ps --status=running ${{ inputs.container-name }} | grep -q '${{ inputs.container-name }}'; then
              docker compose exec ${{ inputs.container-name }} sh -c 'maintenance 0'
              if [ $? != 0 ]
              then
                echo "WARN: Could not disable maintenance mode!"
                echo "WARN: Proceeding with deployment..."
                exit 1
              fi
            else
              echo "WARN: ${{ inputs.container-name }} container is not running!"
              exit 1
            fi
