name: Deploy Neos Compose Project
run-name: Deploy ${{ inputs.version }} to ${{ inputs.environment }}

on:
  workflow_call:
    inputs:
      environment:
        description: "Target Environment"
        type: string
        required: true
      version:
        required: true
        type: string
      ref-type:
        description: "Git ref type: 'tag' or 'branch'. If provided, VERSION override runs only for branches."
        type: string
        required: false
        default: ''
    secrets:
      SSH_HOST:
        required: true
      SSH_PORT:
        required: true
      SSH_USERNAME:
        required: true
      SSH_KEY:
        required: true
      BASIC_AUTH_USERNAME:
        required: false
      BASIC_AUTH_PASSWORD:
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v6

      - name: Enable maintenance
        uses: avency/gh-workflows/.github/actions/maintenance@v3
        with:
          enable: 'true'
          container-name: nginx
          deployment-compose-target: ${{ vars.DEPLOYMENT_COMPOSE_TARGET }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Deploy
        uses: avency/gh-workflows/.github/actions/deploy@v3
        with:
          version: ${{ inputs.version }}
          ref-type: ${{ github.ref_type }}
          deployment-compose-source: ${{ vars.DEPLOYMENT_COMPOSE_SOURCE }}
          deployment-compose-target: ${{ vars.DEPLOYMENT_COMPOSE_TARGET }}
          deployment-environment-source: ${{ vars.DEPLOYMENT_COMPOSE_ENVIRONMENT_SOURCE }}
          deployment-environment-env-filename: ${{ vars.ENV_FILENAME }}
          deployment-compose-do-upgrade: true
          deployment-force-recreate-containers: ${{ vars.DEPLOYMENT_COMPOSE_FORCE_RECREATE_CONTAINERS }}
          backup-do-backup: ${{ vars.DEPLOYMENT_COMPOSE_DO_BACKUP }}
          backup-target-folder: ${{ vars.DEPLOYMENT_COMPOSE_BACKUP_TARGET_FOLDER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Re-Enable maintenance
        uses: avency/gh-workflows/.github/actions/maintenance@v3
        with:
          enable: 'true'
          container-name: nginx
          deployment-compose-target: ${{ vars.DEPLOYMENT_COMPOSE_TARGET }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}

  init:
    needs: [deploy]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Local http check
        if: ${{ vars.DEPLOY_DO_HTTP_CHECK == 'true' }}
        uses: avency/gh-workflows/.github/actions/local-http-check@v3
        with:
          deployment-compose-target: ${{ vars.DEPLOYMENT_COMPOSE_TARGET }}
          domain: ${{ vars.DOMAIN }}
          basic-auth-username: ${{ secrets.BASIC_AUTH_USERNAME }}
          basic-auth-password: ${{ secrets.BASIC_AUTH_PASSWORD }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Clear Cache
        if: ${{ vars.DEPLOY_EXEC_CLEAR_CACHE_WARMUP == 'true' }}
        uses: avency/gh-workflows/.github/actions/neos-clear-cache@v3
        with:
          deployment-compose-target: ${{ vars.DEPLOYMENT_COMPOSE_TARGET }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Migrate Database
        if: ${{ vars.DEPLOY_EXEC_MIGRATE_DATABASE == 'true' }}
        uses: avency/gh-workflows/.github/actions/neos-migrate-database@v3
        with:
          deployment-compose-target: ${{ vars.DEPLOYMENT_COMPOSE_TARGET }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Publish Static Resources
        if: ${{ vars.DEPLOY_EXEC_PUBLISH_RESOURCE == 'true' }}
        uses: avency/gh-workflows/.github/actions/neos-publish-resources@v3
        with:
          deployment-compose-target: ${{ vars.DEPLOYMENT_COMPOSE_TARGET }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Command Migration
        if: ${{ vars.DEPLOY_EXEC_COMMAND_MIGRATION == 'true' }}
        uses: avency/gh-workflows/.github/actions/neos-command-migration@v3
        with:
          deployment-compose-target: ${{ vars.DEPLOYMENT_COMPOSE_TARGET }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Build Elasticsearch Index
        if: ${{ vars.DEPLOY_EXEC_ELASTICSEARCH_INDEX == 'classic' || vars.DEPLOY_EXEC_ELASTICSEARCH_INDEX == 'queue' }}
        uses: avency/gh-workflows/.github/actions/neos-elasticsearch-index@v3
        with:
          deployment-compose-target: ${{ vars.DEPLOYMENT_COMPOSE_TARGET }}
          index-type: ${{ vars.DEPLOY_EXEC_ELASTICSEARCH_INDEX }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}

  finish:
    needs: [init]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Disable maintenance
        uses: avency/gh-workflows/.github/actions/maintenance@v3
        with:
          enable: 'false'
          container-name: nginx
          deployment-compose-target: ${{ vars.DEPLOYMENT_COMPOSE_TARGET }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Check HTTP status
        if: ${{ vars.DOMAIN != '' && vars.DEPLOY_DO_HTTP_CHECK == 'true' }}
        uses: gerdemann/http-status-code@002e9e0a716f4af986d26fc4af4c0a671b3733fc
        with:
          url: ${{ vars.DOMAIN }}
          code: 200
          timeout: 60
          interval: 10
          username: ${{ secrets.BASIC_AUTH_USERNAME }}
          password: ${{ secrets.BASIC_AUTH_PASSWORD }}
