name: Initialize Neos

on:
  workflow_call:
    inputs:
      deployment-compose-target:
        description: "Target path on the remote server"
        type: string
        required: true
      domain:
        description: "Domain to check for HTTP status"
        type: string
        required: true
      deploy-do-http-check:
        description: "Run an HTTP check for status code `200` before initialization and after deployment (requires `domain`)"
        type: boolean
        default: true
        required: false
      deploy-exec-clear-cache-warmup:
        description: "Clear and warm up the cache"
        type: boolean
        default: true
        required: false
      deploy-exec-migrate-database:
        description: "Run database migrations"
        type: boolean
        default: true
        required: false
      deploy-exec-publish-resource:
        description: "Publish all static resources"
        type: boolean
        default: true
        required: false
      deploy-exec-command-migration:
        description: "Run command migrations"
        type: boolean
        default: false
        required: false
      deploy-exec-elasticsearch-index:
        description: "Which Elasticsearch index operation to run: 'false' (none), 'classic', or 'queue'"
        type: string
        default: 'false'
        required: false
    secrets:
      SSH_HOST:
        required: true
      SSH_PORT:
        required: true
      SSH_USERNAME:
        required: true
      SSH_KEY:
        required: true

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Local http check
        if: ${{ inputs.deploy-do-http-check }}
        uses: avency/gh-workflows/.github/actions/local-http-check@v2
        with:
          deployment-compose-target: ${{ inputs.deployment-compose-target }}
          domain: ${{ inputs.domain }}
          basic-auth-username: ${{ secrets.BASIC_AUTH_USERNAME }}
          basic-auth-password: ${{ secrets.BASIC_AUTH_PASSWORD }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Clear Cache
        if: ${{ inputs.deploy-exec-clear-cache-warmup }}
        uses: avency/gh-workflows/.github/actions/neos-clear-cache@v2
        with:
          deployment-compose-target: ${{ inputs.deployment-compose-target }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Migrate Database
        if: ${{ inputs.deploy-exec-migrate-database }}
        uses: avency/gh-workflows/.github/actions/neos-migrate-database@v2
        with:
          deployment-compose-target: ${{ inputs.deployment-compose-target }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Publish Static Resources
        if: ${{ inputs.deploy-exec-publish-resource }}
        uses: avency/gh-workflows/.github/actions/neos-publish-resources@v2
        with:
          deployment-compose-target: ${{ inputs.deployment-compose-target }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Command Migration
        if: ${{ inputs.deploy-exec-command-migration }}
        uses: avency/gh-workflows/.github/actions/neos-command-migration@v2
        with:
          deployment-compose-target: ${{ inputs.deployment-compose-target }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Build Elasticsearch Index
        if: ${{ inputs.deploy-exec-elasticsearch-index == 'classic' || inputs.deploy-exec-elasticsearch-index == 'queue' }}
        uses: avency/gh-workflows/.github/actions/neos-elasticsearch-index@v2
        with:
          deployment-compose-target: ${{ inputs.deployment-compose-target }}
          index-type: ${{ inputs.deploy-exec-elasticsearch-index }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
