name: Initialize Neos
run-name: Initialize Neos for ${{ inputs.environment }}

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      compose-service-name:
        required: false
        type: string
        default: 'php'
      compose-service-user:
        required: false
        type: string
        default: 'www-data'
    secrets:
      SSH_HOST:
        required: true
      SSH_PORT:
        required: true
      SSH_USERNAME:
        required: true
      SSH_KEY:
        required: true
jobs:
  init:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:
      - name: Check HTTP status with httpcheck.sh
        if: ${{ vars.DOMAIN != '' && vars.DEPLOY_DO_HTTP_CHECK == 'true' }}
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          timeout: "300s"
          script: |
            cd ${{ vars.DEPLOYMENT_COMPOSE_TARGET }}/
            if [ -f ./httpcheck.sh ]; then
              chmod u+x ./httpcheck.sh
              ./httpcheck.sh --url=${{ vars.DOMAIN }} --interval=10
              if [ $? != 0 ]
              then
                 exit 1
              fi
            else
              echo "WARN: httpcheck.sh does not exist, skipping HTTP check. Please add it to the target directory."
            fi

      - name: Clear cache and warmup cache
        if: ${{ vars.DEPLOY_EXEC_CLEAR_CACHE_WARMUP == 'true' }}
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          timeout: "60s"
          script: |
            cd ${{ vars.DEPLOYMENT_COMPOSE_TARGET }}/
            docker compose exec -u ${{ inputs.compose-service-user }} ${{ inputs.compose-service-name }}  sh -c "/data/flow flow:cache:flush && /data/flow flow:cache:warmup"
            if [ $? != 0 ]
            then
               exit 1
            fi

      - name: Migrate database
        if: ${{ vars.DEPLOY_EXEC_MIGRATE_DATABASE == 'true' }}
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          timeout: "60s"
          script: |
            cd ${{ vars.DEPLOYMENT_COMPOSE_TARGET }}/
            docker compose exec -u ${{ inputs.compose-service-user }} ${{ inputs.compose-service-name }} sh -c "/data/flow doctrine:migrate"
            if [ $? != 0 ]
            then
               exit 1
            fi

      - name: Publish resources
        if: ${{ vars.DEPLOY_EXEC_PUBLISH_RESOURCE == 'true' }}
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          timeout: 120s
          script: |
            cd ${{ vars.DEPLOYMENT_COMPOSE_TARGET }}/
            docker compose exec -u ${{ inputs.compose-service-user }} ${{ inputs.compose-service-name }} sh -c "/data/flow flow:resource:publish --collection static"
            if [ $? != 0 ]
            then
               exit 1
            fi

      - name: Execute Command Migrations
        if: ${{ vars.DEPLOY_EXEC_COMMAND_MIGRATION == 'true' }}
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          timeout: 120s
          script: |
            cd ${{ vars.DEPLOYMENT_COMPOSE_TARGET }}/
            docker compose exec -u ${{ inputs.compose-service-user }} ${{ inputs.compose-service-name }} sh -c "/data/flow commandmigration:migrate"
            if [ $? != 0 ]
            then
               exit 1
            fi

      - name: Build Elasticsearch Index (Classic)
        if: ${{ vars.DEPLOY_EXEC_ELASTICSEARCH_INDEX == 'true' }}
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          timeout: 120s
          script: |
            cd ${{ vars.DEPLOYMENT_COMPOSE_TARGET }}/
            docker compose exec -u ${{ inputs.compose-service-user }} ${{ inputs.compose-service-name }} sh -c "/data/flow nodeindex:build --workspace live"
            if [ $? != 0 ]
            then
               exit 1
            fi

      - name: Build Elasticsearch Index (Queue)
        if: ${{ vars.DEPLOY_EXEC_ELASTICSEARCH_QUEUE == 'true' }}
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          timeout: 120s
          script: |
            cd ${{ vars.DEPLOYMENT_COMPOSE_TARGET }}/
            docker compose exec -u ${{ inputs.compose-service-user }} ${{ inputs.compose-service-name }} sh -c "/data/flow nodeindexqueue:flush"
            if [ $? != 0 ]
            then
               exit 1
            fi

            docker compose exec -u ${{ inputs.compose-service-user }} ${{ inputs.compose-service-name }} sh -c "/data/flow nodeindexqueue:build --workspace live"
            if [ $? != 0 ]
            then
               exit 1
            fi
